### ISSUE TITLE
Polymer imported from wrong location

### ISSUE THREAD

**Issue by Artur-** [vaadin/components#102]
Loading vaadin-components from http://localhost:8888/foobar/bower_components/vaadin-components/vaadin-components.html tries to load http://localhost:8888/foobar/bower_components/bower_components/polymer/polymer.html. Should be http://localhost:8888/foobar/bower_components/polymer/polymer.html

**Comment by Peppe-** [comment]
Sounds as the same case as #76. Seems fixed to me as I can't find bower_components in the urls in either https://github.com/vaadin-bower/vaadin-components/blob/master/vaadin-grid/vaadin-grid.html or  https://github.com/vaadin-bower/vaadin-components/blob/7451e585d2a8750594278e10f61f4cd66b77f0bb/vaadin-components.html

**Comment by Artur-** [comment]
Seems to be fixed in 0.3.0-beta6, but that version is not what you get by default with bower install. You get 0.3.0-snapshot, which is 0.3.0-beta5.
