### ISSUE TITLE
Grid with only headers not shown

### ISSUE THREAD

**Issue by Artur-** [vaadin/components#103]
```
<v-grid> 
  <table>
    <colgroup>
      <col header-text="First column">
      <col header-text="Second column">
    </colgroup>
    <tbody>
    </tbody>
  </table>
</v-grid>
```

Would expect this to render an empty grid with two headers. It renders a horizontal line.

**Comment by tomivirkki** [comment]
http://jsfiddle.net/fz4kr4fm/
Works for me

**Comment by Artur-** [comment]
Maybe #85, as the grid was inside a flex box

**Comment by jounik** [comment]
Please try with beta6 and reopen if you still have the same problem.
