### ISSUE TITLE
Selection checkbox checkmark is not aligned properly in IE 11

### ISSUE THREAD

**Issue by jounik** [vaadin/components#129]
Firefox (correct):
![screenshot 2015-09-02 23 55 35](https://cloud.githubusercontent.com/assets/66382/9644146/4e7d074e-51ce-11e5-9335-27d1aa5c5571.png)

IE11 (incorrect):
![screenshot 2015-09-02 23 55 21](https://cloud.githubusercontent.com/assets/66382/9644154/593b6888-51ce-11e5-8b9a-c281e753fca8.png)

**Comment by cwayfinder** [comment]
The checkboxes align seems equal in my Firefox and IE11 (Windows 10)


![Screenshot](http://i.imgur.com/9LpJgB0.png)
