### ISSUE TITLE
Column hiding dropdown broken in IE11

### ISSUE THREAD

**Issue by jounik** [vaadin/components#130]
The column hiding dropdown menu icon is missing: 
![screenshot 2015-09-02 23 59 37](https://cloud.githubusercontent.com/assets/66382/9644239/b06c45fa-51ce-11e5-85ee-14392531e9b2.png)

Clicking the column hiding dropdown menu button crashes IE 11 every time: 
![ie11-crash](http://g.recordit.co/L5ul007hr1.gif)

**Comment by cwayfinder** [comment]
Cannot reproduce on Windows 10 and IE11


![Screenshot](http://i.imgur.com/juSs62n.png)

**Comment by jounik** [comment]
I was kind of expecting that. I’ll ask someone else to test on a virtual machine as well. I was using Windows 8.1.

**Comment by tomivirkki** [comment]
Occurs on my virtual machine also (Win 8.1)

**Comment by jounik** [comment]
From Guillermo:
“IE11 windows 7 vm the button is not visible and then IE stops working
IE11 windows 8.1 vm the button is not visible but column hiding works”

**Comment by cwayfinder** [comment]
Fixed the icon appearance. Cannot reproduce IE crash in Windows 7
