### ISSUE TITLE
IE: Column hiding menu shadow/border is too light

### ISSUE THREAD

**Issue by tepi** [vaadin/components#141]
See screenshot; Chrome on left, IE11 on right.
![screen shot 2015-09-08 at 11 21 14](https://cloud.githubusercontent.com/assets/1527900/9730314/5d63445e-561e-11e5-9cda-ea9ebf35f013.png)

**Comment by jounik** [comment]
Change the box-shadow blur value from `5px` to `6px` in the last value here:
https://github.com/vaadin/components/blob/master/vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html#L566
