### ISSUE TITLE
Replacing `grid.columns` causes selection column to flex

### ISSUE THREAD

**Issue by jounik** [vaadin/components#17]
Replacing `grid.columns` causes selection column to flex also like other columns (takes more space than necessary). Hovering over the grid fixes the width.

Happens at least in Chrome.

**Comment by tepi** [comment]
Can't reproduce with latest master (using vaadin-widgets 7.5.3).

**Comment by jounik** [comment]
Can’t reproduce anymore either.

**Comment by jounik** [comment]
This seems to have been fixed in some earlier version already, but I’m marking it for 0.3.0 final.
