### ISSUE TITLE
Using inside chrome packaged app

### ISSUE THREAD

**Issue by kzahel** [vaadin/components#20]
I wanted to try out vaadin-grid inside a Chrome packaged app, but VaadinGridImport.nocache.js attempts to do a document.write (not allowed) which throws an exception and causes everything to break.

Also it modifies document.onbeforeunload, etc, which will also not work.

Also why is this file obfuscated? Is there an un-obfuscated version that I can use easily?

**Comment by Saulis** [comment]
Hi!

Unfortunately I'm not familiar with Chrome Package Apps, but if #16 causes them to break, we need to investigate it further. 

`<v-grid>` is based on the [Vaadin Framework Grid](http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid) component and it's implemented in Java using GWT. It's compiled into minified/obfuscated Javascript by default, and in our case `VaadinGridImport.nocache.js` the size goes down `~248KB` from `~902KB` normal version.

If it helps, you can clone vaadin/components and run `gulp gwt --gwt-pretty` to compile a prettified version. You can join our [Gitter](https://gitter.im/vaadin/components?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) chat if you need further instructions.

**Comment by cwayfinder** [comment]
Issue with document.write has been resolved. See https://github.com/vaadin/components/issues/16 for details. Please let us know how this works for you.
