### ISSUE TITLE
Empty strings cause grid to crash in Internet Explorer

### ISSUE THREAD

**Issue by chimon2000** [vaadin/components#25]
Verified in Edge version:
If you are binding to a list of objects like `[{color: 'red', type: 'volvo', year: ''}]` or arrays like `[['red', 'volvo', '']]` empty string values causes IE to crash epically. This only happens when developer tools are closed, which makes it near impossible to debug.

**Comment by jounik** [comment]
Thanks for the report. We’ll investigate if this happens in any other browser as well.

**Comment by tomivirkki** [comment]
Can't reproduce this issue. https://jsfiddle.net/r1162gsz/ works fine on Edge. There's a strange scrollbar in the last cell but that's another issue. Please provide a jsfiddle that reproduces the crash and re-open this ticket if the problem still exists.
