### ISSUE TITLE
Horizontal scrollbar is hidden when scrolling vertically (OS X Chrome)

### ISSUE THREAD

**Issue by jounik** [vaadin/components#29]

**Comment by tomivirkki** [comment]
Does this still occur? Can't reproduce.

**Comment by jounik** [comment]
Sorry, erroneous title for the issue (fixed now).

Still happens using master.

**Comment by Saulis** [comment]
I can verify that the issue is reproducible in Chrome 43, however only on a non-retina display. Issue can also be seen in [Vaadin Sampler](http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features) on non-Valo themes.

**Comment by tomivirkki** [comment]
Reported a framework issue here https://dev.vaadin.com/ticket/18376
