### ISSUE TITLE
Removing attribute selected-rows throws an Error

### ISSUE THREAD

**Issue by Saulis** [vaadin/components#3]
Given a `<v-grid selected-rows="0"></v-grid>` 

Removing the attribute from DOM or with JS `grid.removeAttribute('selected-rows');`

Throws:
`Error: Uncaught TypeError: Cannot read property 'split' of null (/Users/Saulis/Dev/components/vaadin-components/vaadin-grid/vaadin-grid.html:40)`

Instead, should set `grid.selectedRows` to `[]` or `undefined`

Test located [here](https://github.com/vaadin/components/blob/master/vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-selecting.html#L109)

**Comment by manolo** [comment]
In review: https://dev.vaadin.com/review/#/c/8461/

**Comment by jounik** [comment]
Clean up old test issue.
