### ISSUE TITLE
Chrome OS X hides scrollbars even if System Preferences has "Show scrollbars always" on

### ISSUE THREAD

**Issue by jounik** [vaadin/components#30]

**Comment by anezthes** [comment]
Seems to work for me. Tested vaadin-components/vaadin-grid/demo.html with OS X scroll bar settings set to "always" show.

**Comment by tomivirkki** [comment]
Can verify the issue. Here's the fix https://dev.vaadin.com/review/#/c/11355/

**Comment by tomivirkki** [comment]
Actually, seems that it only occurs on superdevmode. Jouni can you confirm?

**Comment by tomivirkki** [comment]
Ooh, I'll take that back. It's quite apparent in the examples http://vaadin.github.io/components-examples/v-grid/datasources.html
