### ISSUE TITLE
Wrong checkbox style state

### ISSUE THREAD

**Issue by amahdy** [vaadin/components#32]
- In the demo, go to example "9" (Selection)
- Select an element then unselect it: the checkbox color weight is higher than others.
- Now scroll a bit down, you will see other checkboxes with the same style.

Basically the reused row (checkbox) keeps the style state which is wrong.

**Comment by jounik** [comment]
I can’t seem to reproduce this. Could you either present very clear steps to reproduce, or add a screencast of how to do it?

**Comment by amahdy** [comment]
Easier way to reproduce is to focus using "Tab" as your comment on #36 then scroll.

It results in random different checkboxes that get focus.
