### ISSUE TITLE
Calling grid.data.source = newArray is slow and had multiple renders

### ISSUE THREAD

**Issue by Peppe-** [vaadin/components#67]
I have a grid which gets pushed data all the time, something like once per two seconds. It is always the same columns and ten rows of data. if I just call ```grid.data.source = newArray``` then the rendering takes 650ms and has deferred calls, which means that it blinks as it first renders a blank version of the grid and then re-adds all the data to it.

The alternative to replacing the array is to manually update the array, here's my code:
```javascript
if(!grid.data.source){
  grid.data.source = newArray
} else {
  newArray.forEach(function(point, index){
    grid.data.source[index][0] = point[0];
    grid.data.source[index][1] = point[1];
  });
}
```
With this code instead the time to rerender goes down to 150ms and and there is no timers causing partial renders, thus no blinking

Issues at hand:
1) The user should not need to know tricks like this. It is something that the component itself should handle. ```grid.data.source = newArray``` should be just as quick as this workaround.

2) There shouldn't be timers in the rendering, causing partial renders. I wouldn't have minded the issue so much if the grid wouldn't have blinked all the time when the data changes

3) Both 650ms and 150ms is quite long times to just update a ten row grid with two text columns with no extra features turned on. My CPU fan starts ramping up when I'm just viewing the view and that has made me consider switching out to a standard html \<table\>. Something like 10ms for a case like this is something to reach for.

**Comment by manolo** [comment]
Fixed.
