### ISSUE TITLE
Bower packaged vaadin-grid.html has erroneous relative path for polymer.html

### ISSUE THREAD

**Issue by jounik** [vaadin/components#76]
In `vaadin-grid.html` the relative path is specified as `../../bower_components/polymer/polymer.html`, which doesn’t work when installed from Bower.

The path should be `../../polymer/polymer.html`.

This probably depends on the packaging script which also does the CDN and ZIP packages.

**Comment by jounik** [comment]
Seems like it was broken in the last beta5 release:

Beta4: https://github.com/vaadin-bower/vaadin-components/blob/0.3.0-beta4/vaadin-grid/vaadin-grid.html#L5

Beta5: https://github.com/vaadin-bower/vaadin-components/blob/0.3.0-beta5/vaadin-grid/vaadin-grid.html#L5

**Comment by tepi** [comment]
The path was manually changed by Manolo in https://github.com/vaadin-bower/vaadin-components/commit/7451e585d2a8750594278e10f61f4cd66b77f0bb
No idea why but the path change has been reverted now.
