### ISSUE TITLE
How to wrap long lines

### ISSUE THREAD

**Issue by naseer** [vaadin/components#97]
Firstly - thank you for this amazing component!

I have a cell renderer which prints a bunch of links using the <a> tag.  I wanted to break to a new line after each link but it didn't work. Is this supported?

**Comment by jounik** [comment]
Hi, thanks for the feedback!

Unfortunately, v-grid only supports equal height rows, so you have to make each row tall enough to accommodate two lines of links, even though there would only be one row of links in some of them.

Variable height rows are in the backlog, but there’s no schedule for it right now.

**Comment by naseer** [comment]
Thank you - I will try this. I'm hoping it will pick up the line break and go to the next line if the row is tall enough.

**Comment by jounik** [comment]
Closing as a non-issue. You can ask for more help here still if you wish.
